.gitignore, Project.toml, src/ParametricOptInterface.jl, test/production_problem_test.jl, test/quadratic_tests.jl, test/runtests.jl
=> Current version of POI

src/ParametricOptInterface.jl, src/utils.jl
- organized the codebase in smaller functions
=> Better support for scalar quadratic functions

Project.toml, src/ParametricOptInterface.jl, test/jump_tests.jl
This fix broken tests and fixes #48
=> fix broken tests

src/ParametricOptInterface.jl, src/duals.jl
=> Fix 32bit sys tests

benchmark/benchmark.jl, docs/src/example.md, docs/src/manual.md, src/ParametricOptInterface.jl, src/duals.jl, src/update_parameters.jl, src/utils.jl, test/basic_tests.jl, test/jump_tests.jl, test/production_problem_test.jl, test/quad_tests.jl, test/vector_affine_tests.jl
The naming did not follow MOI best-practice.
=> [breaking] Rename ParametricOptimizer to Optimizer

src/ParametricOptInterface.jl, src/duals.jl, src/update_parameters.jl, src/utils.jl
To get myself oriented, I read through the code making minor style improvements as I went.
=> Maintenance: general improvements to code style

Project.toml, src/ParametricOptInterface.jl, src/utils.jl, test/MOI_wrapper.jl, test/runtests.jl
I rewrote the changes @jd-lara had implemented in his PR and added a few extra functions to pass the MOI tests
It's still in progress though
=> Replaces #59

src/ParametricOptInterface.jl, src/utils.jl, test/runtests.jl
small rewrite of some code-blocks for better readability
=> Simplify function has parameters code blocks

src/ParametricOptInterface.jl, src/update_parameters.jl, src/utils.jl
=> Use DoubleDicts instead of Dicts

src/ParametricOptInterface.jl, src/utils.jl, test/MOI_wrapper.jl, test/quad_tests.jl
=> Fix MOI.ListOfConstraintTypesPresent function

src/ParametricOptInterface.jl, src/update_parameters.jl, src/utils.jl, test/MOI_wrapper.jl
I also updated some of the MOI_wrapper tests and fixed some modification calls (Use `MOI.modify` instead of rewriting objectives because of a constant change.)
=> Add Clever Dicts to parameters

src/ParametricOptInterface.jl, test/jump_tests.jl
=> Fix prints in some cases of direct model

docs/src/example.md, docs/src/reference.md, src/ParametricOptInterface.jl, src/duals.jl, src/update_parameters.jl, test/basic_tests.jl, test/jump_tests.jl
=> Add possibility to interpret parametric expressions as bounds

docs/make.jl, docs/src/Examples/benders.md, docs/src/Examples/example.md, docs/src/Examples/markowitz.md
- Benders Decomposition of Quantile Regression
- Markowitz Portfolio Optimization
=> Add new examples

src/ParametricOptInterface.jl
=> Evaluate duals only if available

src/ParametricOptInterface.jl, test/jump_tests.jl
=> Add `AbstractVariableAttribute` fallback

src/ParametricOptInterface.jl, test/basic_tests.jl
=> Add `ListOfPureVariableIndices` and `ListOfParametersIndices` attributes

Project.toml, src/ParametricOptInterface.jl, test/jump_tests.jl
=> Fix getter and add tests

Project.toml, test/Project.toml
It makes it easier to test locally IMO
=> Add test Project.toml

Project.toml, src/MOI_wrapper.jl, test/jump_tests.jl
=> Fix deletion methods

Project.toml, src/MOI_wrapper.jl, src/ParametricOptInterface.jl, src/duals.jl, src/parametric_functions.jl, src/update_parameters.jl, test/jump_tests.jl, test/moi_tests.jl
=> Fixes for DiffOpt
