Project.toml
src/ParametricOptInterface.jl
test/jump_tests.jl
test/runtests.jl

closes #1 
- Creation of necessary functions in order to interact with the JuMP interface, e.g MOI.is_empty, MOI.get, MOI.set, MOI.supports
- Creation of mutable struct 'ParameterValue' which is used to assign value to parameters
- Correction of a bug in which a ScalarQuadraticFunction was not treated as a ScalarAffineFunction when the quadratic term was a product of 2 parameters
- Added some tests with JuMP
```julia
optimizer = POI.ParametricOptimizer(GLPK.Optimizer())
c = [4.0, 3.0]
A1 = [2.0, 1.0, 1.0]
A2 = [1.0, 2.0, 1.0]
b1 = 4.0
b2 = 4.0
model = direct_model(optimizer)
@variable(model, x[i=1:2] >= 0)
@variable(model, y in POI.Parameter(0))
@variable(model, w in POI.Parameter(0))
@variable(model, z in POI.Parameter(0))
@constraint(model, 2*x[1] + x[2] + y <= 4)
@constraint(model, …
```

Added functions to interact with JuMP

---

.gitignore
Project.toml
README.md
benchmark/Project.toml
benchmark/benchmark.jl
docs/make.jl
src/ParametricOptInterface.jl
test/runtests.jl

Current comparison against master
```
========== Results ==========
add_constraint
BenchmarkTools.TrialJudgement: 
time:   -10.68% => improvement (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_constraint_sqf_2
BenchmarkTools.TrialJudgement: 
time:   -8.57% => improvement (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_variable_constraints
BenchmarkTools.TrialJudgement: 
time:   -4.12% => invariant (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_variables
BenchmarkTools.TrialJudgement: 
time:   -4.23% => invariant (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_variable
BenchmarkTools.TrialJudgement: 
time:   -2.10% => invariant (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance) …
```

Small fixes

---

src/ParametricOptInterface.jl

- Creates a function that empties the objective function cache
- Fixes where `Float64` appeared instead of `T`

Fix small issues

---

benchmark/benchmark.jl
src/ParametricOptInterface.jl
src/utils.jl
test/production_problem_test.jl

We made checking if a MOI.VariableIndex is a variable or a parameter faster and made some better function barriers.
I think that these reports are not too reliable, depending on the run they give opposite results... Anyways, here they are
========== Results ==========
add_constraint
BenchmarkTools.TrialJudgement: 
time:   -1.75% => invariant (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_constraint_sqf_2
BenchmarkTools.TrialJudgement: 
time:   +13.86% => regression (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_variable_constraints
BenchmarkTools.TrialJudgement: 
time:   -24.59% => improvement (5.00% tolerance)
memory: +0.00% => invariant (1.00% tolerance)
add_variables
BenchmarkTools.TrialJudgement: 
time:   -13.33% => improvement (5.00% …

Clever indexing

---

.github/workflows/ci.yml
.github/workflows/documentation.yml
benchmark/benchmark.jl
src/duals.jl
src/update_parameters.jl
src/utils.jl
test/MOI_wrapper.jl
test/basic_tests.jl
test/production_problem_test.jl
test/quad_tests.jl

Following: https://github.com/jump-dev/ParametricOptInterface.jl/commit/c75210a2a411d4bb22db73a7ab9cecb0066730cb

MOI 1.0, format check, CI

---

benchmark/Manifest.toml
benchmark/run_benchmarks.jl

The updates benchmarks were a bit misleading, now we can understand better the price of updating the objective 100 times and updating 100 constraints once. These benchmarks are more helpful to understand POI overhead than the previous ones.

Fix misleading benchmarks

---

src/ParametricOptInterface.jl

Fix named constraints Error with Gurobi/CPLEX

---

benchmark/Manifest.toml
src/ParametricOptInterface.jl
src/update_parameters.jl
src/utils.jl

Fix Gurobi update problem

---

docs/src/manual.md
src/ParametricOptInterface.jl
src/duals.jl
src/update_parameters.jl
src/utils.jl
test/jump_tests.jl
test/moi_tests.jl
test/runtests.jl

Large refactor

---

Project.toml
src/ParametricOptInterface.jl
test/jump_tests.jl

Add getter and setters for AbstractOptimizerAttribute

---

benchmark/MOI_benchmarks.jl
benchmark/run_benchmarks.jl
benchmark/run_benchmarks_jump.jl
benchmark/run_benders_quantile_regression_benchmark.jl
docs/make.jl
src/duals.jl
src/utils.jl
test/jump_tests.jl
test/moi_tests.jl

Protect query of multiplicative duals and fix objective term on duals

---

Project.toml
README.md
benchmark/MOI_benchmarks.jl
benchmark/run_benchmarks.jl
benchmark/run_benchmarks_jump.jl
benchmark/run_benders_quantile_regression_benchmark.jl
docs/src/Examples/benders.md
docs/src/Examples/example.md
docs/src/Examples/markowitz.md
docs/src/manual.md
docs/src/reference.md
src/ParametricOptInterface.jl
src/duals.jl
test/jump_tests.jl
test/moi_tests.jl

close #132 
close #136
replaces #139 
replaces #137

Switch to MOI.Parameter and fixes tests

---

docs/src/Examples/example.md
src/MOI_wrapper.jl
test/jump_tests.jl

Closes https://github.com/jump-dev/ParametricOptInterface.jl/issues/146
Closes #149
We actually don't support the `NLPBlock` because POI re-orders the variables by removing parameters. The tests passed because they had parameters at the end. But that isn't a good solution, and it seems simpler to drop support for the legacy nonlinear interface than throw an error if parameters are not in the right order.
We also don't really need POI for nonlinear. Ipopt supports parameters directly.

[breaking] drop invalid nonlinear support

---

src/MOI_wrapper.jl
test/jump_tests.jl

Fix MOI.get for quadratic constraints

---

src/MOI_wrapper.jl
src/duals.jl
test/moi_tests.jl

Replace "Dual solution not available" warning in `MOI.optimize!` with an error in `MOI.get`. Otherwise, a warning is shown even when duals are not requested.

Remove dual solution warning from optimize!

---

src/MOI_wrapper.jl
test/moi_tests.jl

When alternating between constraints with and without parameters, the `model.constraint_outer_to_inner` Dict would lose track of the constraint indexes. 
In the new test, without the changes, the dual for c2 returns -3.0.

Update constraint indexes when adding constraints without parameters

---

src/MOI_wrapper.jl
test/moi_tests.jl

I am playing around using POI with SumOfSquares and was hitting an error for `f - g * p` if `p` is a parameter and `g` has less monomials than `f`. Indeed, this will create scalar quadratic constraint with no quadratic term and with no parameter which currently fails.
This PR should fix it

Convert quadratic to affine even when there is no parameters

---

src/MOI_wrapper.jl

Thanks for the great package! I found this small typo when looking through the docs -- the example has `InterpretConstraintsAsBounds` instead of `ConstraintsInterpretation`.

Fix ConstraintsInterpretation docstring

---

src/MOI_wrapper.jl
test/jump_tests.jl
test/moi_tests.jl

improves coverage in https://github.com/jump-dev/ParametricOptInterface.jl/pull/178

Improve coverage

---

docs/src/manual.md
src/MOI_wrapper.jl
src/ParametricOptInterface.jl
test/Project.toml
test/jump_tests.jl
test/moi_tests.jl
test/runtests.jl

Fix map of variables
